-- MySQL Script generated by MySQL Workbench
-- Sat May 25 12:39:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema emprestimo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema emprestimo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `emprestimo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `emprestimo` ;

-- -----------------------------------------------------
-- Table `emprestimo`.`db_amigos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo`.`db_amigos` (
  `amigoid` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `telefone` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`amigoid`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestimo`.`db_ferramentas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo`.`db_ferramentas` (
  `ferramentaid` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `custo` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`ferramentaid`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestimo`.`db_senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo`.`db_senha` (
  `usuarioid` INT NOT NULL AUTO_INCREMENT,
  `senha` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`usuarioid`),
  INDEX `usuarioid_idx` (`usuarioid` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `emprestimo`.`db_emprestimos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `emprestimo`.`db_emprestimos` (
  `emprestimoid` INT NOT NULL AUTO_INCREMENT,
  `amigoid` INT NULL DEFAULT NULL,
  `ferramentaid` INT NULL DEFAULT NULL,
  `usuarioid` INT NULL DEFAULT NULL,
  `data_emprestimo` VARCHAR(10) NULL DEFAULT NULL,
  `data_devolucao` VARCHAR(10) NULL DEFAULT NULL,
  `senha_usuario` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`emprestimoid`),
  INDEX `amigoid_idx` (`amigoid` ASC) VISIBLE,
  INDEX `ferramentaid_idx` (`ferramentaid` ASC) VISIBLE,
  INDEX `usuarioid_idx` (`usuarioid` ASC) VISIBLE,
  CONSTRAINT `amigoid`
    FOREIGN KEY (`amigoid`)
    REFERENCES `emprestimo`.`db_amigos` (`amigoid`),
  CONSTRAINT `ferramentaid`
    FOREIGN KEY (`ferramentaid`)
    REFERENCES `emprestimo`.`db_ferramentas` (`ferramentaid`),
  CONSTRAINT `usuarioid`
    FOREIGN KEY (`usuarioid`)
    REFERENCES `emprestimo`.`db_senha` (`usuarioid`))
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
